### ISSUE TITLE
Current TODO list

### ISSUE THREAD

**Issue by jk-jeon** [jk-jeon/fp#1]
- [ ] Add CI scripts.
- [ ] Implement fixed-point/general formatting routines.
- [ ] Correctly implement policies.
- [ ] Test against Microsoft STL's `<charconv>` dataset.
- [ ] Determine between header-only and static library; properly separate things that will reside in headers and things that will be compiled.
- [ ] Write documents on algorithm/implementation.
- [ ] Write documents on API.

**Comment by sirinath** [comment]
Looking to see how things are progressing.

**Comment by sirinath** [comment]
I think the following items to be priority items in priority order:

1. Implement fixed-point/general formatting routines.
1. Correctly implement policies. Implement an interface of to_binary_limited_precision and ryu_printf specialized for the usage in unlimited-precision parsing. (Avoid needless packing into/extracting from IEEE-754 formats.)
1. Turn from_chars_unlimited_precision into one-pass for limited precision, two-pass for unlimited precision.
1. Optimize from_chars_limited_precision and from_chars_unlimited_precision.
1. Think of an algorithm for fixed-precision binary-to-decimal conversion that use fewer amount of static data; it is desirable to make it less than 10KB. (Currently, it is possible to get about 26KB by tweaking Ryu-printf a bit.)
1. Write documents on algorithm/implementation.
1. Write documents on API.
